# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (C) 2016 Imagination Technologies
# Author: Paul Burton <paul.burton@mips.com>
#

#obj-y += init.o

obj-$(CONFIG_MACH_JZ4740)		+= jz4740gpio.o
